version: "3"

services:
  app:
    depends_on:
      - db
    user: node
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile.development
      args:
        CHINA_MIRROR: "true"
    volumes:
      - .:/home/node
      # - py-pkgs:/home/user/.local/lib/python3.10/site-packages
    env_file:
      - .env.local
    command: yarn start:dev
    ports:
      - 3001:3001

  db:
    hostname: db
    image: postgres:14-alpine
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/pgsql:/docker-entrypoint-initdb.d
      - postgresql:/var/lib/postgresql/data
  
  # redis:
  #   image: "redis:6-2-alpine"

volumes:
  postgresql:
